<?php

namespace Laratube;

use Illuminate\Database\Eloquent\Model as BaseModel;
use Illuminate\Support\Str;

class Model extends BaseModel
{
    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            // $model->id = Str::uuid();

            // Flexible cho trường hợp bảng đó ko dùng 'id' làm primary key mà dùng tên khác bất kỳ.
            $model->{$model->getKeyName()} = (string) Str::uuid();
        });
    }
}
